---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-admin-creds
  namespace: nextcloud
spec:
  encryptedData:
    password: AgBgi6cy0bM5XAEmePVcUFQlQgeFOVHjjV8C2stazRmuWPYKFSMuy2DroWQFIMW6xTmp3g+qdAOtc2IzL47YulUSyAanSVk5s2k7TxROP3+Nvlilcw9dKy+ckv/Orxh+O2N+zyl1ihvw7Z3w3CwlUH7NfdPH8FM2A6UuVL3xxNuvkzA3LuUJn4LWboBwAJhuh1WJJdHqrq6JWxMBZ6QY33lhE2YshxE7TCjGvX7wG3t+nF/+KMjyK4i6YyoPopdelypaUXw2kDrJ3xqqGZP3bUmanEv17yfaizUgbhVQW755TUb0dF2oAil6v+pvGlPmAW2dqipbsYR3cfH62RKkBtnny8pJyqt2IVJAiV2pclL4befh66wWUkjqJnh6Jg6Zc6aLLdS0CAjz7aszk/97Du2K1xTJpvtzSUweXEOaahc0loXleKkMiufRDCdWwUaH32bRXt0vpkjiEvHLK8XkvHooZcD2woOa3xZqVObC7gyhj91qlDnDYTY4diB+r68hoPt0TU8mXoiGKqxliNOjt0I40KcnBeh+5ZvkP6KHyjHTi3psxAHW64hERz78yYVSBaWBupLT3mMzbPkkfvjKz9MkXA0RvznIpzFloL3ec1aqCMoXOhVjP18LElWLMDrwHNfZFT95iyqb+0Cryuj+u0kuxfoHe+d/zu0AEQGEIxOcBAu7AU35yBjkPDcQurm2xk6nuyghAe5Bekioj+H7rOs/ptXNULag7qGylpvPn8r79A==
    username: AgCpxxFIq+KlkdlPJWsjn6pcIqhTJEEq15XYULow6WIwnLUpdMaZoFAQBopF9jjrPCeCaoc1LdSOEJnk0PpuFgm+3gdujjkfzXZZ4aoazHHpu+C/9mR6hZ2XwcwVGlSPy48BpXhlK8R6g4IBMsPXMR1BP7ip12dckPvGiR7myCwJS1vtzJ49iXsmtqIkHGLsPXg7erdUBlQjnV2Pc/NxvWrWZ/D8GcGA5v6Jse0C2fzM4Qi4ieaHyqWdM/A9u/Gy7rdXSCfZJnu0wIi3QYbUIscWvRNCrebLCPaI+cvhB1znLe+JcX2p678Fz7vTFvk2+WxpOx/hilS9p+aT9ITjilYTk9jZhqaTeObDOry/tU/O8prOxGRP7vvQ7YoDE9iK0P865vYfreI2w5WxitDcnHiA1vY7zYH3WaFBDx1QVCmDO/Xcb0YL+iUacjbZ+mOl+iAhfRSrcQ3y/ZXi2wQGxXqWeIB/Jp9fnAQGdF/6drQioiJLx6eIoZDuhGcrVnroK92wkEB4aHKdkcL/g1gkpxi7/FnAoUqcuu6vIJYteLbMwauy0dCQYNcSRLKmdkgt0WWufBKEpXIYWbjcdpll+gi5J5p52MPd2jWrwjgcM+ZIPEVEDbTfp2kGbdTSbUT6+bIJcICd2MWIIvEkLf1C1hEnYfIlMXE0ASYRROQyTadxL78P1CNtdgiHLnQb1C6SyqCfswZdGg==
  template:
    metadata:
      name: nextcloud-admin-creds
      namespace: nextcloud
