---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-redis-creds
  namespace: nextcloud
spec:
  encryptedData:
    redis-password: AgBX9b0+nd5GWhy1pBO81tzkVgPoSDlFu5KlkUTUS3Et/qlsHetoaLt3Gzwbi/5OfRWvUJ2JaoJl3kdTu116+rinM8ZrwLAnnzGy14/qPmmVutJ4hltSMtDap3sTHBwom8IseCWEVfFZuA2wQm4w7zljGNa2sn1DuBygkbXb9fDKE+S+PLWs+prKAMsmvnDnUDiyGdAPhIHoMI8vBWUeXb/rMzjKgLrvm8RBXJlT+XZWY+foQftotbutH0Q8k0FebBt+xKQGQMFdZFc6/rfbFXxEfiAeqWjqbPv48ZM33eqpg3kVPF6ks0UXCVDd1c07QJvYJM1+OI6cHye2T2Uh9NPsXrq66Z8inGqZKpdQrfTd0ygIh6Vuf40cLctVKGwE/l9LPnaZQI/L6VzlcayFDN2/xEzELxj4l75lmPJTOcNqVZK1TOcGNmzeEVy3JojKjXRDt2gIoQzNuSW0eNJuazJbh98fqK0ha3TlARViZMbodZvLh/iwGcacubzZ2b1KUTtMUn7z9d1xSzKugjnS76lHUIYi7LRtLqJ7NkKq4tcJvvMyTfNJNVJfEsCx1pQky5Ng5/KBdF23BqcFiEY3vVBRoVoY3U5TL9+1sVuPUXy8bml4kWnZ/csXEnoGu++COaYUQMM+5t3D2dnpFzr+q2cpgc81qBzPJu720qlB7955mI1TzbOEbjbCyCDq/uYyN9oGTVet/besDq9LfP/W5Ua9JlYKsFyJfO6WERL7NWc=
  template:
    metadata:
      name: nextcloud-redis-creds
      namespace: nextcloud
