apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: garlicdoor
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: oci://ghcr.io/hugz6/garlicdoor/garlicdoor
      chart: garlicdoor
      targetRevision: 1.0.0
      helm:
        releaseName: garlicdoor-portal
        valueFiles:
          - $values/argocd/apps/garlicdoor/values.yaml
    - repoURL: https://github.com/hugz6/petra-homelab-apps.git
      targetRevision: main
      path: argocd/apps/garlicdoor/ingress/
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: garlicdoor

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
