apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: authentik-outpost-embedded-tls
  namespace: authentik
spec:
  secretName: authentik-outpost-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: home.beutra.fr
  dnsNames:
  - home.beutra.fr
