apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: onedev-auth
  namespace: onedev
spec:
  forwardAuth:
    address: http://ak-outpost-authentik-embedded-outpost.authentik.svc.cluster.local:9000/outpost.goauthentik.io/auth/traefik
    trustForwardHeader: true
    authResponseHeaders:
      - Set-Cookie
      - X-authentik-username
      - X-authentik-groups
      - X-authentik-email
      - X-authentik-name
      - X-authentik-uid
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: onedev-ingress
  namespace: onedev
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.middlewares: "onedev-onedev-auth@kubernetescrd"
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.name: "session-sticky"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - onedev.beutra.fr
      secretName: onedev-tls
  rules:
    - host: onedev.beutra.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: onedev-onedev
                port:
                  number: 6610
