apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authelia
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.authelia.com
      chart: authelia
      targetRevision: 0.10.49
      helm:
        releaseName: authelia
        valueFiles:
          - $values/argocd/infra/authelia/values.yaml
    - repoURL: https://github.com/hugz6/petra-homelab-apps.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/hugz6/petra-homelab-apps.git
      targetRevision: main
      path: argocd/infra/authelia/resources
  destination:
    server: https://kubernetes.default.svc
    namespace: authelia
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
