---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-secret
  namespace: minio
spec:
  encryptedData:
    rootPassword: AgA5/JkB3hsFUNW0jOUL7kLK3C6mj7MtFwB4Pu2zTZu9shtI6vrn+wHZv1R9w/gB3F1wosZskZac+ZdCXcQt2bNVgECMn2M6voRC1O2cDoM3SwGHqr+5ep3GGbWMvhduYdUwE+rOXhyVp9hLiE9p3QoMDsj9yFRXJ7wixXlZMJpkOkB3IgyObG9VCNA9kZBAm7epN+bB9WvKO23/IX6t0FtMgt05xBnw7copEfVG7fjT6iK1aE4C9zSyQ2qz6Jv04FOAzOY7VayjGIIcY+ZBFbwwoMtGwwdDfarVsBGYKHFXnxqMxll7Tq85CNtL8tn2p6gaKJkFYLcVWkNsp1Io8f5IrCH47ablGBcaFuDQ5Wx8KohCqReFfxbw7gW9EdFQ+Uw6E4S8CfZWgdinr0vnZUU3iPvimHEyDIMcJpGVlYdp+o5NjmQf0+MYWHx7lS9X2/NsI+tdVRLk1UKtPRpu08S93gTxait2h8/a3qMOwNq2LJduy8kVm9bOWkB0NIqiOFbNqmN+bn6/1OaGIeo3RrRlYZLg4CwESsZUIVjosvxtnQ++2PLs1mL6SIImUigZ51Ud2hyw/JMZOR+3cSLtQ+Q7JIxI/7GIZtauamBjt+mPGni8B0MzPR3slPSpPrXYfrNuJuzoN0qtww6C49nnJNMX16SGjLovktbbtYDa6y21s+HDaEZ3DwWGKBjMnqbXBawzr4MXODwPPa1oC+CE863+PayXjwVGSskj+W41PRrbCQ==
    rootUser: AgCXiRm1T0RivRdI9Qj6579v9HiR3xun+qjCwsFbdYEkcJno9WTOU5ei4b/mfaElD7KwAEH5D8NBoKc/6lDVM+TvKvnclurAi413PLuWmpWwmmNzIEIO/Tj+EHeZW0oDAxsxUH+lgbWMqFh6CM/EFwl9iZoiC2zbD2x8DaPRNmb3f057vvkw8uMO07owsee9F4g7NY8KntLTfr3Z9bBJWwTRXMQGiF22z2AktTj79971JvDkudV5mXNlAVOQoMLpH03Tp21s3BjQeFnlDfNeOJT0WWNhwr2ZJwS1ZyhLimMP+scsu9skSpyD14aNqhzkBTdohMTlN6dv0r2VfcZaaB4x+TMa3jZZaF+6NV0Szh0erP5ZrIi6NjMZs6vT2RwwoqrILZVIKz4WtTTSpPOKYUFNef/+uOB6x2bKplvTsf2RZmLPMdALgwGwfsVdbE3LIyMGyOfnAremSBS9HrFuyYuWM7PazJ+GI3swOjYwfnIEq3Mwwho/ROUsW7RU2ajQqc13507jrJsfPKqRMR0Cbh21f2GDx2s4GB1SQp8MssagHOQ3VpAhJNoW7OwVifeOAff5TqcVFmfS8ONDh2mrNlJMqTmN9Cbt5Rar+nMb+rS3i1LbmGmkkNI5B1Gx+ihO0Vi6XWOI9zkvC3w2kXABUcHD9mViM9Y0h+RhawMCRiZ3Oj1U7O/JfF8QPXd9JO6RuWc56P1+
  template:
    metadata:
      name: minio-secret
      namespace: minio
