apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frp-client
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: oci://ghcr.io/hugz6/frp
      chart: frp
      targetRevision: 0.1.0
      helm:
        releaseName: frp-client
        valueFiles:
          - $values/kubernetes/infra/frp/values.yaml
    - repoURL: https://github.com/hugz6/petra-homelab.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: frp

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
