apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openobserve
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.openobserve.ai
      chart: openobserve
      targetRevision: 0.40.1
      helm:
        valueFiles:
          - $values/kubernetes/infra/openobserve/values.yaml
    - repoURL: https://github.com/hugz6/petra-homelab.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: openobserve
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
