---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: authentik-forwardauth
  namespace: garlicdoor
spec:
  forwardAuth:
    address: http://ak-outpost-garlicdoor-outpost.authentik.svc.cluster.local:9000/outpost.goauthentik.io/auth/traefik
    trustForwardHeader: true
    authResponseHeaders:
      - Set-Cookie
      - X-authentik-username
      - X-authentik-groups
      - X-authentik-email
      - X-authentik-name
      - X-authentik-uid
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: garlicdoor-ingress
  namespace: garlicdoor
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.middlewares: "garlicdoor-authentik-forwardauth@kubernetescrd"
spec:
  ingressClassName: traefik

  tls:
  - hosts:
    - home.beutra.fr
    secretName: garlicdoor-tls

  rules:
  - host: home.beutra.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: garlicdoor-portal
            port:
              number: 80