---
nameOverride: vkms

vmagent:
  spec:
    scrapeInterval: "60s"
    externalLabels:
      cluster: "homelab"

vmsingle:
  spec:
    retentionPeriod: "3d"
    replicaCount: 1
    resources:
      limits:
        memory: "512Mi"
    storage:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "longhorn-single"
      resources:
        requests:
          storage: 10Gi

grafana:
  enabled: true
  admin:
    existingSecret: "grafana-secrets"
    passwordKey: "admin-password"
  persistence:
    enabled: true
    size: 2Gi
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
      - grafana.beutra.fr
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.beutra.fr
  grafana.ini:
    auth.generic_oauth:
      enabled: "true"
      name: "Authentik"
      allow_sign_up: "true"
      client_id: "grafana"
      client_secret: "$__env{GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET}"
      scopes: "openid profile email"
      auth_url: "https://auth.beutra.fr/application/o/authorize/"
      token_url: "https://auth.beutra.fr/application/o/token/"
      api_url: "https://auth.beutra.fr/application/o/userinfo/"
      role_attribute_path: "contains(groups, 'grafana-admins') && 'Admin' || contains(groups, 'grafana-editors') && 'Editor' || 'Viewer'"
  envFromSecret: "grafana-secrets"

vmalert:
  spec:
    extraArgs:
      notifier.blackhole: "true"

alertmanager:
  enabled: false