---
nameOverride: vkms

vmagent:
  spec:
    scrapeInterval: "60s"
    externalLabels:
      cluster: "homelab"

vmsingle:
  spec:
    retentionPeriod: "3d"
    replicaCount: 1
    resources:
      limits:
        memory: "512Mi"
    storage:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
        storageClassName: "longhorn-single"

grafana:
  enabled: true
  adminPassword:
    existingSecret: "grafana-secrets"
    existingSecretKey: "admin-password"
  persistence:
    enabled: true
    size: 2Gi

alertmanager:
  enabled: false