apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://nextcloud.github.io/helm/
      chart: nextcloud
      targetRevision: 8.5.2
      helm:
        releaseName: nextcloud
        valueFiles:
          - $values/kubernetes/apps/nextcloud/values.yaml

    - repoURL: https://github.com/hugz6/petra-homelab.git
      targetRevision: main
      path: kubernetes/apps/nextcloud/
      ref: values

    - repoURL: https://github.com/hugz6/petra-homelab.git
      targetRevision: main
      path: kubernetes/apps/nextcloud/secrets/

    - repoURL: https://github.com/hugz6/petra-homelab.git
      targetRevision: main
      path: kubernetes/apps/nextcloud/ingress/

  destination:
    server: https://kubernetes.default.svc
    namespace: nextcloud

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
