---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: frp-secret
  namespace: frp
spec:
  encryptedData:
    token: AgB0hdXetsAJokd8lNyIQEPKf8k4+7QA6x+C6C/E6Yj9ERWsJ3Vm7u8XbIRKPpgHQwNdf9wpKY2awvYXSCUWVs7YCyk8K+mZuNhTOV7oaYa0N1J1DvYbYHNRaH/uDpQKD/qLb6bWteVE9jEsvn9zcD8hoDbgAs6QvZZedIzaekj9EBCYwMgRCC6+AWXLCEYmZ/XelLCak/TYdBsRYiZSWmHUZyexd8mSPIHEQvykgetOSK4Zq8+GTgXw9vN1X6gUcAl8q05urOAqMdKOT6U8ovke2y078sleykGYXkM3Le4Q+3bBHI/HYexNCsiBSTRFKl36RUdvBY9gpazQpgjSzJ9RNlAy/8kjZyxvFtORYHlyGjzddHFdIqluCqTojiXBkjhzUhgMMWohggu2z3PfBhj+vODoWy4iixNQeshN7A1C+s915nYsdWLBhthmzPX55/v4Nb4XzPLbI6TpI6o+ow/6AnmxAo3e1GDwBHJSgZQT2qCse9wt3LYb4FYIYypEyBCAYmN2BWfamOwaXrgUcyL0uysjvQ/UvRQCnampyhA6H51SCtT0gQakuU4HknsG3UX7xswlhLGN039e0BGVpnMXIjE1jc51XYSaHg0eWlNDggp5V3cZU6ESzPoe3j+Lqr1mp0JihhgHfTh+zbT9KU/PrR1m9jEd9ZiVY5MML7lP5Xsuob8vN1pMnxFnNipYlubEUf1TnHkoE0alfXhzxXl8ABu/RpDKS+33dRT7TyBKPTbaiVgcD6ZTBOYQE4Rw78ENOPqEqrJrgRyqsg4NcpzBGt5Q9fdvyaL/VPBLfAfDbT99NCq9ZJfwiDZrEL5A0V1zNwwLSj3FzKF1gFseWWt5ZfGLI6qYlFUwLWXcuHD5Wg==
  template:
    metadata:
      name: frp-secret
      namespace: frp
