---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: frp-secret
  namespace: frp
spec:
  encryptedData:
    token: AgCJ3H9MoNsWaHMdkckrboLVXgwr+x2LEUHEca64yLA/RiTVd8pcTZvJQAjCHgOtDfyAsblXsnIcLW9NPsgCbwGv0H5BdseTYi5lFldULSFOanIjQKpcDPRb25l5ewzkxGt5CSdob1ALcEXp4ArhxEPN8Z9ALzlkcgH5lftPmCwACDlOJShCxsLAe0DSuZtRXTwdDfp+1Vx8r3vHQZgTp5b56W6QrIqpLEvURlQnpNesG40EdcA65Bu6KG/pyO6FvGVkHBPmGM3qHHz+Cc+fxp99W4z22npjwzNGCAQYDyjYTegWnYUzghD9pelKQYQnXr5p5y1mc1BosJJTDlN1KeTJFyyx3YoRenNjCXNk6Otve/2/0zzRox0f8wUfBqCQlTFg2cjL6t0Ugs8Voxg7D2XBgSFLV6fdo001BAhHSZvrSw2cpa7ZzSGHPckazwtWRn8R+kbEgfEe9ruhdLRHZ1eUcbw25UjxFKoXjQqWKsdAH6ddBqstQ1hpJ2PW7uhGwXlaJ/+XTVh2hgMbYTsGfSQr5Za7CkOIopgnoC/xex52T02FsMc+DAePyATiCclkNn/WASCeFpuSbbCX1yrcwEPqvXTVtOcdglcErL9QB8OEfGBW0mqqq6qMz7A8DKJ9SQpN3NTbMsjwWau219s5MAIcPhaW5Jypq9+KlBlLJyn/TqMw7kfahWX3jZv9myfhl3lb96Jn0XY/tXTOCQLf652EKtfzVqY3I/U3uTTaeIBQe5lFAUPE7Wg/mb/zdkf0nKYpEqlRAJWbvTah9L207wUDyDRgpXsI6nIKrVtwRpv0FiVJ/H0azwqaKiK40e/w34Lfjr2RpLyJWs+2HY8BCArfLrhzMlLEEIc7cib5vnXSMQ==
  template:
    metadata:
      name: frp-secret
      namespace: frp
