apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: garlicdoor-ingress
  namespace: garlicdoor
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/auth-url: |-
        http://authentik-embedded-outpost.authentik.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
    nginx.ingress.kubernetes.io/auth-signin: |-
        https://auth.beutra.fr/outpost.goauthentik.io/start?rd=$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-response-headers: |-
        Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
spec:
  ingressClassName: nginx
  
  tls:
  - hosts:
    - home.beutra.fr
    secretName: garlicdoor-tls

  rules:
  - host: home.beutra.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: garlicdoor-portal
            port:
              number: 80