apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: garlicdoor-ingress
  namespace: garlicdoor
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  
  tls:
  - hosts:
    - home.beutra.fr
    secretName: garlicdoor-tls

  rules:
  - host: home.beutra.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: garlicdoor-portal
            port:
              number: 80