apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-tunnel
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://helm.strrl.dev
      chart: cloudflare-tunnel-ingress-controller
      targetRevision: 0.0.21
      helm:
        values: |
          cloudflare:
            secretRef:
              name: cloudflare-api
              accountIDKey: accountId
              tunnelNameKey: tunnelName
              apiTokenKey: apiToken
          replicaCount: 2

          cloudflared:
            image:
              tag: 2024.6.1
            replicaCount: 2
    - repoURL: https://github.com/hugz6/petra-homelab.git
      targetRevision: main
      path: kubernetes/infra/cloudflare/secrets/
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflare
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
