apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: signoz
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.signoz.io
      targetRevision: 0.106.0
      chart: signoz
      helm:
        valueFiles:
          - $values/kubernetes/apps/signoz/values.yaml
    - repoURL: https://github.com/hugz6/petra-homelab.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: signoz
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true