apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frp-client
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: oci://ghcr.io/hugz6/frp/frp
      chart: frp
      targetRevision: 0.1.2
      helm:
        releaseName: frp-client
        valueFiles:
          - $values/argocd/infra/frp/values.yaml
    - repoURL: https://github.com/hugz6/petra-homelab-apps.git
      path: argocd/infra/frp/secrets
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: frp

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
